### ISSUE TITLE
Uncaught Exception @ Startup on OSX

### ISSUE THREAD

**Issue by bazzinotti** [MediaFire/mediafire-cpp-sdk#5]
Hi I'm using OSX Yosemite 10.10.3 with Macports.. 
I've used macports to install openssl @1.0.2a and Boost @1.58.0_3

however, when I compile my own upload program or build the OSX version. It compiles with modifications but when I run I receive the following: 

libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >: add_certificate_authority: cert already in hash table

**Comment by herbert-jones-mediafire** [comment]
I believe this should fix the problem when building under macports.
